---

- name: Simple AAP Playbook
  hosts: all
  become: yes  # Ensures the tasks are run with elevated privileges (sudo)
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes
